const VendorArr = [
	"jquery",
	"react",
	"react-router",
	"babel-polyfill",
	"react-redux",
	"react-dom",
	"react-addons-css-transition-group",
	"redux",
	"redux-thunk",
	"redux-logger",
	"axios",
	"react-router-redux",
	// "numeral",
	"moment",
	"react-google-login-component",
	"react-form",
	"react-helmet",
	// "striptags",
	"react-ga",
	"markdown-it",
	"recharts",
	"isomorphic-style-loader/lib/withStyles",
	"js-cookie"
];
export default  VendorArr;
